name: Run Python Script (BRT schedule)

on:
  schedule:
    # Executa às 00h, 06h, 12h e 18h BRT
    - cron: "0 3,9,13,21 * * *"
  workflow_dispatch: # permite rodar manualmente também

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      - name: Run script
        run: python scraper.py